#!/bin/bash

while [[ ! -e /var/run/mysqld/mysqld.sock ]]; do sleep 1; done

while true; do
/usr/bin/mysql -u root <<EOF
create database slurm_acct_db;
create user 'slurm'@'localhost';
set password for 'slurm'@'localhost' = password('slurmdbpass');
grant usage on *.* to 'slurm'@'localhost';
grant all privileges on slurm_acct_db.* to 'slurm'@'localhost';
flush privileges;
exit
EOF
test "$?" = "0" && break
sleep 1
done

/usr/sbin/slurmdbd -D
