"""Add email

Revision ID: 20210921
Revises: 20210804
Create Date: 2021-09-21 21:21:51.709350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20210921'
down_revision = '20210804'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('owl_user', sa.Column('email', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('owl_user', 'email')
    # ### end Alembic commands ###
